- .dev/.mailpitpsswd
- .env.example
- README.md
- docker-compose.yml
> ci: add mailpit service

- frontend/modules/shared/ui/src/lib/layout/sidebar/sidebar.component.html
- frontend/modules/shared/ui/src/lib/layout/sidebar/sidebar.component.ts
- frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.html
- frontend/modules/shared/ui/src/lib/ui.module.ts
- frontend/src/app/app.module.ts
- frontend/src/app/root.component.html
- frontend/src/app/root.component.less
- frontend/src/app/root.component.ts
0 clue how to implement it closing on route change XD
i hope ive abstracted it in the correct place and really sorry if i didn't I have 0 confidence in my angular skills XD
> Collapsable sidebar on mobile

- frontend/modules/admin/src/lib/page/feature/page-list/page-list.component.ts
- frontend/modules/admin/src/lib/shared/util/resource-search-wrapper.ts
- frontend/src/assets/i18n/en.json
> Custom template in resource search wrapper

- backend/src/main/java/com/example/cms/security/authentication/RestAuthenticationSuccessHandler.java
- backend/src/main/java/com/example/cms/user/User.java
- backend/src/main/java/com/example/cms/user/UserService.java
- backend/src/main/java/com/example/cms/user/projections/UserDtoDetailed.java
- backend/src/main/java/com/example/cms/user/projections/UserDtoSimple.java
- frontend/modules/admin/src/lib/admin.style.less
- frontend/modules/admin/src/lib/user/feature/user-details/user-details.component.html
- frontend/modules/admin/src/lib/user/feature/user-list/user-list.component.html
- frontend/modules/admin/src/lib/user/feature/user-list/user-list.component.ts
- frontend/modules/shared/data-access/src/lib/models/user.ts
- frontend/src/assets/i18n/en.json
> Add last login date to user

- frontend/modules/shared/ui/src/lib/layout/search/search.component.html
- frontend/modules/shared/ui/src/lib/layout/search/search.component.ts
- frontend/modules/shared/ui/src/lib/layout/sidebar/sidebar.component.html
- frontend/modules/shared/ui/src/lib/layout/sidebar/sidebar.component.ts
- frontend/src/app/app.module.ts
- frontend/src/app/root.component.html
Fixes collapsing sidebar when clicking dropdown inside
Fixes #67
> Fix sidebar active zone

- frontend/modules/auth/src/lib/features/login-shell/login-shell.component.html
- frontend/modules/shared/security/src/lib/auth.service.ts
- frontend/modules/shared/security/src/lib/user.directive.ts
> Fix user directive no start value and auth guard cache size

- frontend/modules/admin/src/lib/lib.routes.ts
- frontend/modules/shared/ui/src/lib/layout/language-switcher/language-switcher.component.ts
- frontend/modules/shared/util/src/index.ts
- frontend/modules/shared/util/src/lib/lang/translated-title.resolve.ts
- frontend/src/app/app-routing.module.ts
- frontend/src/app/university/university-routing.module.ts
- frontend/src/assets/i18n/en.json
> Make breadcrumbs translateable

- README.md
- backend/src/main/java/com/example/cms/development/DummyDataCreator.java
- backend/src/main/java/com/example/cms/keywords/KeyWordsController.java
- backend/src/main/java/com/example/cms/page/projections/PageDtoFormCreate.java
- backend/src/main/java/com/example/cms/page/projections/PageDtoFormUpdate.java
- backend/src/main/java/com/example/cms/template/TemplateController.java
- backend/src/main/java/com/example/cms/template/TemplateService.java
- backend/src/main/java/com/example/cms/template/TemplateSpecification.java
- backend/src/main/java/com/example/cms/template/projections/TemplateDtoFormCreate.java
- backend/src/main/java/com/example/cms/template/projections/TemplateDtoFormUpdate.java
- backend/src/main/java/com/example/cms/university/projections/UniversityDtoFormUpdate.java
- backend/src/test/java/com/example/cms/page/PageControllerTest.java
- frontend/modules/admin/src/lib/dashboard/tiles.ts
- frontend/modules/admin/src/lib/keyword/feature/keyword-create-form/keyword-create-form.component.ts
- frontend/modules/admin/src/lib/shared/editor-extensions/load-template/load-template.component.ts
- frontend/modules/shared/data-access/src/lib/api.params.ts
- frontend/modules/shared/data-access/src/lib/services/key-words.service.ts
- frontend/modules/shared/data-access/src/lib/services/page.service.ts
- frontend/modules/shared/data-access/src/lib/services/template.service.ts
> Merge api actions

- backend/src/main/java/com/example/cms/development/DummyDataCreator.java
- backend/src/main/java/com/example/cms/page/Page.java
- backend/src/main/java/com/example/cms/page/PageController.java
- backend/src/main/java/com/example/cms/page/PageService.java
- backend/src/main/java/com/example/cms/page/projections/PageDtoFormUpdate.java
- backend/src/main/java/com/example/cms/ticket/Ticket.java
- backend/src/main/java/com/example/cms/ticket/TicketRepository.java
- backend/src/main/java/com/example/cms/ticket/TicketService.java
- backend/src/main/java/com/example/cms/ticket/TicketSpecification.java
- backend/src/main/java/com/example/cms/ticket/projections/TicketDto.java
- backend/src/main/java/com/example/cms/user/User.java
- backend/src/main/java/com/example/cms/user/UserService.java
- backend/src/main/java/com/example/cms/user/exceptions/UserNotFound.java
> feat: option to assign somone to page

- frontend/modules/admin/src/lib/page/feature/page-create-form/page-create-form.component.html
- frontend/modules/admin/src/lib/page/feature/page-create-form/page-create-form.component.ts
- frontend/modules/admin/src/lib/page/feature/page-details/page-details.component.html
- frontend/modules/admin/src/lib/page/feature/page-details/page-details.component.ts
- frontend/modules/admin/src/lib/page/feature/page-edit-form/page-edit-form.component.html
- frontend/modules/admin/src/lib/page/feature/page-edit-form/page-edit-form.component.ts
- frontend/modules/admin/src/lib/university/feature/university-edit-form/university-edit-form.component.html
- frontend/modules/admin/src/lib/university/feature/university-edit-form/university-edit-form.component.ts
- frontend/modules/admin/src/lib/user/feature/user-edit-form/user-edit-form.component.html
- frontend/modules/admin/src/lib/user/feature/user-edit-form/user-edit-form.component.ts
- frontend/modules/shared/ui/src/lib/directives/confirm.directive.ts
- frontend/modules/shared/util/src/lib/rxjs/map-to-api-resource.ts
- frontend/src/assets/i18n/en.json
> Add missing confirm dialogs

- backend/src/main/java/com/example/cms/ticket/TicketService.java
- backend/src/main/java/com/example/cms/ticket/projections/TicketDtoDetailed.java
> feat: lastSeenOn is now returned in ticket detailed

- backend/src/main/java/com/example/cms/development/DummyDataCreator.java
- backend/src/main/java/com/example/cms/template/Template.java
- backend/src/main/java/com/example/cms/template/TemplateService.java
- backend/src/main/java/com/example/cms/template/TemplateSpecification.java
- backend/src/main/java/com/example/cms/template/projections/TemplateDtoDetailed.java
- backend/src/main/java/com/example/cms/template/projections/TemplateDtoFormCreate.java
- backend/src/main/java/com/example/cms/template/projections/TemplateDtoFormUpdate.java
- frontend/modules/admin/src/lib/template/feature/template-create-form/template-create-form.component.html
- frontend/modules/admin/src/lib/template/feature/template-create-form/template-create-form.component.ts
- frontend/modules/admin/src/lib/template/feature/template-details/template-details.component.html
- frontend/modules/admin/src/lib/template/feature/template-edit-form/template-edit-form.component.html
- frontend/modules/admin/src/lib/template/feature/template-edit-form/template-edit-form.component.ts
- frontend/modules/shared/data-access/src/lib/models/template.ts
- frontend/src/assets/i18n/en.json
> Add template availability for all

- backend/src/main/java/com/example/cms/development/DummyDataCreator.java
- backend/src/main/java/com/example/cms/user/UserService.java
- backend/src/main/java/com/example/cms/user/projections/UserDtoFormCreate.java
- backend/src/main/java/com/example/cms/user/projections/UserDtoFormUpdate.java
- frontend/modules/shared/data-access/src/lib/services/user.service.ts
* Merge user PATCH actions into one PUT (Closes #109)
* Add possibility to reset User password by admin (Closes #28)
> Merge user patch actions, reset password by admin

- backend/src/main/java/com/example/cms/backup/BackupService.java
- backend/src/main/java/com/example/cms/security/SecurityConfig.java
- backend/src/main/java/com/example/cms/security/authentication/RestAuthenticationFilter.java
- frontend/e2e/src/support/commands.ts
- frontend/modules/shared/security/src/lib/auth.service.ts
- frontend/src/app/app.module.ts
* Enabled spring CSRF protection (Closes #64)
* Removed CodeQL reported vulnerabilities:
* Logging password in cypress tests (quite unused but good to know)
* Path traversal vulnerability in `BackupService` and `ZipService`
> Security fixes

- backend/src/main/java/com/example/cms/university/UniversityController.java
- backend/src/main/java/com/example/cms/university/UniversityService.java
- backend/src/test/java/com/example/cms/BaseAPIControllerTest.java
- backend/src/test/java/com/example/cms/page/PageControllerTest.java
- backend/src/test/java/com/example/cms/university/UniversityControllerTest.java
- frontend/e2e/src/e2e/main_administrator.cy.ts
> Add university API tests

- backend/pom.xml
- backend/src/main/java/com/example/cms/page/PageRepository.java
- backend/src/main/java/com/example/cms/search/FullTextSearchService.java
- backend/src/main/java/com/example/cms/search/services/DummyPageFullTextSearchService.java
- backend/src/main/java/com/example/cms/search/services/PageFullTextSearchService.java
- backend/src/main/java/com/example/cms/university/UniversityService.java
> Fix typesense data synchronization

- .github/workflows/cicd.yml
- backend/src/main/java/com/example/cms/university/UniversityService.java
- backend/src/test/java/com/example/cms/BaseAPIControllerTest.java
- backend/src/test/java/com/example/cms/university/UniversityControllerTest.java
> Add get universities tests

- frontend/modules/admin/src/lib/admin.module.ts
- frontend/modules/admin/src/lib/page/feature/page-edit-form/page-edit-form.component.html
- frontend/modules/admin/src/lib/page/feature/page-edit-form/page-edit-form.component.ts
- frontend/modules/admin/src/lib/shared/editor-extensions/html-editor/html-editor.component.html
- frontend/modules/admin/src/lib/shared/editor-extensions/html-editor/html-editor.component.less
- frontend/modules/admin/src/lib/shared/editor-extensions/html-editor/html-editor.component.ts
- frontend/modules/admin/src/lib/shared/editor-extensions/html-editor/html-editor.extension.ts
- frontend/modules/admin/src/lib/shared/editor-extensions/load-template/load-template.component.ts
- frontend/modules/shared/util/src/lib/forms/form-submit-wrapper.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/assets/i18n/en.json
- frontend/src/assets/i18n/pl.json
> Add html editor

- frontend/modules/shared/data-access/src/lib/services/page.service.ts
- frontend/modules/shared/data-access/src/lib/services/ticket.service.ts
- frontend/src/app/ticket/ticket.component.html
- frontend/src/app/university/feature/page-contact-form/page-contact-form.component.html
- frontend/src/app/university/feature/page-contact-form/page-contact-form.component.ts
Bumped question length to 2000 as 255 seemed very little, I wonder if we need this sort of limit in the first place.
> Create ticket api integration

- backend/src/main/java/com/example/cms/email/EmailSendingService.java
> fix: Replace localhost with APP_URL setting in email templates

- backend/src/main/java/com/example/cms/ticket/TicketService.java
- backend/src/main/java/com/example/cms/ticket/UnseenTicketSpecification.java
- backend/src/main/java/com/example/cms/ticketUserStatus/TicketUserStatus.java
- frontend/modules/shared/ui/src/lib/layout/notifications/notifications.component.html
- frontend/modules/shared/ui/src/lib/layout/notifications/notifications.component.scss
- frontend/src/app/ticket/ticket.component.ts
- frontend/src/styles.less
Fixes #200 
- Ticket info revalidation on message send
- Add pointer events none to badge
- Fix last seen on for non contact request handlers
> Misc ticket bugs

- frontend/modules/shared/ui/src/lib/layout/notifications/notifications.component.html
- frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.html
- frontend/modules/shared/ui/src/lib/layout/top-bar/top-bar.component.scss
- frontend/src/assets/i18n/en.json
- frontend/src/assets/i18n/pl.json
- frontend/src/index.html
- frontend/src/styles.less
> Add user info to logged in dropdown

- LICENSE
- README.md
- backend/src/main/java/com/example/cms/configuration/CustomApplicationConfiguration.java
- backend/src/main/java/com/example/cms/user/UserController.java
- backend/src/main/java/com/example/cms/user/UserService.java
- frontend/default.conf
- frontend/modules/admin/src/lib/ticket/feature/ticket-list/ticket-list.component.html
- frontend/modules/shared/security/src/lib/auth.service.ts
Closes #235 
Closes #237 
Closes #234
Closes #238
> General fixes

- backend/src/main/java/put/eunice/cms/resource/FileResourceService.java
- backend/src/test/java/put/eunice/cms/resource/ResourceControllerTest.java
> feat: Add security checks to resources

- backend/src/main/java/put/eunice/cms/search/FullTextSearchFeeder.java
- backend/src/main/java/put/eunice/cms/search/services/PageFullTextSearchService.java
makes sure that visible pages are added to typesense at startup
> feat: add typesense feeder at application start
